# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fd2c5ad43f706cdbe0b09ee883d0badd567b0342a6679476ef936826f340efb86fa57c1c92405d656084b102f145e2ac6f590e2ee3d52b78f33c4ade8a7bf84

test:
  secret_key_base: 2931774c99e24ae6ad9de3f051d3f2c7a0d5d18ebe2aaf9d4731ea400e4e1ef24cb95009cd6e9317ff0b79923563cd3bfab68ce8ab46a43d81f43eec7340b512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
